resources:
 containers:
   - container: terraform
     image: hashicorp/terraform
     options: --entrypoint=""


trigger: none
pr: none

jobs:
  - job: terraform
    container: terraform
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
         terraform init
         terraform plan -out terraform.plan
         terraform apply -f terraform.plan
        workingDirectory: 'terraforms/infra'