trigger: none
pr: none

jobs:
  - job: terraform
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
         docker run -v $(pwd):/src hashicorp/terraform:latest -chdir=/src init
         docker run -v $(pwd):/src hashicorp/terraform:latest -chdir=/src plan -out terraform.plan
         docker run -v $(pwd):/src hashicorp/terraform:latest -chdir=/src apply terraform.plan
        workingDirectory: 'terraforms/infra'